import Head from "next/head";
import React from "react";
import styles from "../styles/Index.module.scss";
import VeritiTable from "../components/veritiTable/VeritiTable";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Veriti test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VeritiTable />
    </div>
  );
}
