import Head from "next/head";
import styles from "../styles/Index.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Veriti test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.container_h1}>Vulnerable Hosts</h1>
    </div>
  );
}
